<?php try {
    if (isset($this->product)) :
        $product = $this->product;
?>
<p><h3><?= $product->getTitle(); ?></h3></p>
<br>
<div class="row">
	<div class="col-xs-6 col-md-4 text-center">
		<img src="<?= $product->getDisplayImage(); ?>" class="img-rounded"/>
		<input type="hidden" name="product_id" id="product_id" value="<?= $product->getId(); ?>">
	</div>
	<div class="col-xs-12 col-md-8">
		<p>
			<?= $product->getDescription(); ?>
		</p>
		<div class="form-group">			
			<label>Model:</label>
			<span class="form-control-static"><?= $product->getModelNumber(); ?></span>
		</div>
		<div class="form-group">
			<label for="">Quantity:</label>
			<input type="text" name="quantity" id="quantity" size="3" value="1" />
		</div>
		<div class="form-group">
			<label>Price:</label>
			<span class="form-control-static"><?= $product->getUnitPrice(); ?></span>
		</div>
		<input type="button" class="btn btn-default" id="addToCartB" value="Add to cart" />
	</div>
</div>
<div class="row">
	<h4>Product Features</h4>
	<p><?= $product->getFeatures(); ?></p>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$('input#addToCartB').on('click', ProdMethods.addToCartClick);
});

ProdMethods = {};

ProdMethods.addToCartClick = function(event) {
	event.preventDefault();
	event.stopPropagation();

	if (!ProdMethods.validate()) {
		return false;
	}

	var productId = $('input#product_id').val();
	var quantity = $('input#quantity').val();
	var url = "<?= $this->url('cart_add_to_cart'); ?>";
	var data = {
            product_id: productId,
            quantity: quantity
        };
    var button = $(this);

        $.ajax( {
        	async: true,
            cache: false,
            type: 'POST',
            url: url,
            dataType: 'json',
            data: data,
            processData: true,
            beforeSend: function() {
                button.attr('disabled', 'disabled');
            }
        }).done( function( data ) {
            if ( data.success === true ) {
                window.location.reload();
            } else {
                alert('Unexpected error occurred');
            }
        }).fail( function() {
        }).always( function() {
        	button.removeAttr('disabled');

        } );
	
};
	
ProdMethods.validate = function() {
	if (isNaN(parseInt($('input#quantity').val()))) {
		alert('Invalid quantity value');
		return false;
	}

	return true;
}

</script>



<?php 
    endif;
} catch(\Exception $e) {
    echo 'Unexpected error occurred';
}
?>