<?php if (isset($this->categories) && !empty($this->categories)) :
    $categories = $this->categories;
?>

<div class="table-responsive">
    <table class="table table-bordered table-striped">
    
		<thead>
			<tr>
				<th style="width: 20%;" class="text-center">Id</th>
				<th style="width: 40%;" class="text-center">Title</th>
				<th style="width: 40%;" class="text-center">Parent</th>
			</tr>
		</thead>
			    
    	<tbody>
    	<?php foreach ($categories as $category) : ?>
    		<tr>
    			<td class="text-center"><?= $category->getId(); ?></td>
    			<td><?= $category->getTitle(); ?></td>
    			<td>
    				<?php if (is_object($parent = $category->getParent())) : ?>
    					<?= $parent->getTitle(); ?>
					<?php endif; ?>
    			</td>
			</tr>
    	<?php endforeach; ?>
    	</tbody>
    </table>
 </div>
 <?php endif; ?>
 