<form name="login_form" method="POST">
    <div class="row text-center">
    	<div class="col-xs-12">
        	<div class="form-group">
        		<label for="username">Username:</label>
        		<input type="text" name="username" />
        	</div>
        	<div class="form-group">
        		<label for="password">Password:</label>
        		<input type="password" name="password"  />
        	</div>
        	
        	<input type="submit" class="btn btn-default" value="Login" />
    	</div>
    </div>
</form>
