<?php
try {
    if (isset($this->loginForm)) :
        $form = $this->loginForm;
        $form->prepare();
?>

    <?= $this->form()->openTag($form); ?>
        <div class="row text-center">
        	<div class="col-xs-12">
        		<?php if (isset($this->loginResult) 
        		        && ($this->loginResult === false)) :?>
        			<div>Login failed.</div> 
        			<br>
    			<?php endif; ?>
            	<div class="form-group">
            		<?= $this->formLabel($form->get('username')); ?>
            		<?= $this->formElement($form->get('username')); ?>
            		<?= $this->formElementErrors($form->get('username')); ?>
            	</div>
            	<div class="form-group">
            		<?= $this->formLabel($form->get('password')); ?>
            		<?= $this->formElement($form->get('password')); ?>
            		<?= $this->formElementErrors($form->get('password')); ?>
            	</div>
            	
            	<input type="submit" class="btn btn-default" value="Login" />
        	</div>
        </div>
	<?= $this->form()->closeTag(); ?>

<?php 
    endif;
} catch (\Exception $e) {
    // @TODO Log error;
    echo 'Unexpected error occurred.';
}
?>